#
# Makefile for the FUSE filesystem.
#

obj-$(CONFIG_FUSE_FS) += fuse.o
obj-$(CONFIG_CUSE) += cuse.o
obj-$(CONFIG_FUSE_STATISTICS) += fuse_stat.o

fuse-objs := dev.o dir.o file.o inode.o control.o xattr.o acl.o readdir.o
